### ISSUE TITLE
Error installing with pip

### ISSUE THREAD

**Issue by tommyod** [metebalci/pdftitle#12]
I get the following error when running `pip install pdftitle`:
```
Collecting pdftitle
  Downloading https://files.pythonhosted.org/packages/e8/dc/2cfe5ebeb595d546e488d3586c92c638fb040e835680ea212413ae94293e/pdftitle-0.4.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/tommy/anaconda3/envs/py37/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jbtqfepv/pdftitle/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jbtqfepv/pdftitle/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-jbtqfepv/pdftitle/pip-egg-info
         cwd: /tmp/pip-install-jbtqfepv/pdftitle/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jbtqfepv/pdftitle/setup.py", line 7, in <module>
        with open(path.join(here, 'README.md'), encoding='utf-8') as f:
      File "/home/tommy/anaconda3/envs/py37/lib/python3.7/codecs.py", line 904, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-install-jbtqfepv/pdftitle/README.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

Seems that `setup.py` wants to get `long_description` from `README.md`, but in the [pypi source files](https://pypi.org/project/pdftitle/#files) the README is not available.

**Comment by metebalci** [comment]
I think it was because the version of setup tools I used last time. It should be ok with v0.5
